### PR TITLE
Update to imgui-v1.81

### PR DESCRIPTION
**Pull request by dvj**
Adds tables support, amongst other things.

Tables work well in imtui without modification, but should likely add a line to the style setup in `ImTui_ImplText_Init()` of something like:
```c
    ImGui::GetStyle().CellPadding             = ImVec2(1,0);
```
to make the tables fit better.

Note as well that Omar did some work on supporting alpha channel in Freetype, which conflicts with storing the character value in the alpha bits of the glyph.

Obviously Freetype and imtui won't overlap, so this isn't a practical issue, but it took me a bit to discover and might break again in the future.

### CODE REVIEW

**Comment by ggerganov** [comment]
Thanks for this!
Do you mind changing the target branch of the PR to [ggerganov:imtui-v1.81](https://github.com/ggerganov/imgui/tree/imtui-v1.81) - I just created it. We should be able to see the diff more cleanly this way.

**Comment by dvj** [comment]
Done. Sorry, I should have done that originally. I noticed there are some unused variables now as well, which I could clean up if desired. Also looks like some duplicated demo code.

I replicated some of the offsets in the parts with conflicts, but I don't know exactly how you came up with some of them, so checking that things still look correct to you would be a good idea. 

All in all, there aren't many changes – which is impressive! There are enough that it makes merging this back into mainline imgui difficult, but that would sure be nice. Some of the changes, such as using ascii symbols for the tree nodes and "X" for window close seem like they could be supported with a mainline version using the `WindowBorderAscii` flag. Other changes, such as the various offsets would be more difficult, but perhaps they could come down to a `style`-type setting, such as `ImGuiStyle.AsciiPadding`, which would normally be 0, except when using the ncurses backend.

Have you discussed this at all with @ocornut?

**Comment by ggerganov** [comment]
> Also looks like some duplicated demo code.

Hmm, not sure where did this come from. Maybe keep the original `imgui_demo.cpp` as of v1.81 ?

> I replicated some of the offsets in the parts with conflicts, but I don't know exactly how you came up with some of them, so checking that things still look correct to you would be a good idea.

Yes, these offsets are one of the nasty things I had to do to get things to look properly in the terminal. I came up with them via trial and error. Need to figure out a better way to do this. For now we can just keep tuning them as we see something that is broken.

> Have you discussed this at all with @ocornut?

Not yet. Main reason is I feel there could be a better way to implement this, instead of using the alpha bits for the characters.
But I agree - it would be great to come up with a reasonable way to merge ascii support back in the mainline repository.

So, after the demo code clean-up I think we can merge this. I will do testing then with ImTui before updating its submodule to v1.81.

**Comment by dvj** [comment]
Removed the duplicated code. Looks right now.

BTW, imgui 1.82 just came out today (bad timing on my part!). But there are only two small conflicts there, and things look ok at first glance, so maybe that will be a nice follow-up just to stay current.

Thanks for your work, it's a really great idea!

**Comment by ggerganov** [comment]
I just created the `imtui-v1.82` branch - PR is welcome.

**Pull request merged**
